### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Jocker666z** [jrosener/aromatic#5]
I have installed dependencies, my dristro is Debian Unstable and :

```
g++ -c -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o utils.o utils.cpp
utils.cpp:10:40: error: return type ‘std::string’ {aka ‘class std::__cxx11::basic_string<char>’} is incomplete
   10 | std::string exec(const std::string &cmd)
      |                                        ^
utils.cpp:10:13: error: ambiguating new declaration of ‘void exec(const string&)’
   10 | std::string exec(const std::string &cmd)
      |             ^~~~
In file included from utils.cpp:4:
utils.h:4:13: note: old declaration ‘std::string exec(const string&)’
    4 | std::string exec(const std::string &cmd);
      |             ^~~~
utils.cpp: In function ‘void exec(const string&)’:
utils.cpp:13:38: error: invalid use of incomplete type ‘const string’ {aka ‘const class std::__cxx11::basic_string<char>’}
   13 |     std::shared_ptr<FILE> pipe(popen(cmd.c_str(), "r"), pclose);
      |                                      ^~~
In file included from /usr/include/c++/10/iosfwd:39,
                 from /usr/include/c++/10/memory:74,
                 from utils.cpp:1:
/usr/include/c++/10/bits/stringfwd.h:74:11: note: declaration of ‘std::string’ {aka ‘class std::__cxx11::basic_string<char>’}
   74 |     class basic_string;
      |           ^~~~~~~~~~~~
utils.cpp:13:32: error: ‘popen’ was not declared in this scope
   13 |     std::shared_ptr<FILE> pipe(popen(cmd.c_str(), "r"), pclose);
      |                                ^~~~~
utils.cpp:13:57: error: ‘pclose’ was not declared in this scope; did you mean ‘clone’?
   13 |     std::shared_ptr<FILE> pipe(popen(cmd.c_str(), "r"), pclose);
      |                                                         ^~~~~~
      |                                                         clone
utils.cpp:21:17: error: variable ‘std::string result’ has initializer but incomplete type
   21 |     std::string result = "";
      |                 ^~~~~~
utils.cpp:22:13: error: ‘feof’ was not declared in this scope
   22 |     while (!feof(pipe.get()))
      |             ^~~~
utils.cpp:24:13: error: ‘fgets’ was not declared in this scope; did you mean ‘fgetws’?
   24 |         if (fgets(buffer, 128, pipe.get()) != NULL)
      |             ^~~~~
      |             fgetws
make: *** [Makefile:501 : utils.o] Erreur 1
```

**Comment by jrosener** [comment]
Strangely it builds well on Ubuntu 20.04. Anyway, I added some missing `#include` in `utils.cpp`, please update and try again.

**Comment by Jocker666z** [comment]
It's work now, many thanks.
